"""households, chores, tags

Revision ID: 0368fa9b08ba
Revises: 4199a0488681
Create Date: 2026-07-16 06:15:29.793925

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0368fa9b08ba"
down_revision: str | Sequence[str] | None = "4199a0488681"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "households",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_households")),
    )
    op.create_table(
        "chores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column(
            "repeats",
            sa.Enum("manual", "daily", "weekly", "monthly", "yearly", name="repeat_period"),
            nullable=False,
        ),
        sa.Column(
            "assignment_type",
            sa.Enum("manual", "alphabetical", "random", "least_done", name="assignment_type"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_chores_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chores")),
    )
    op.create_table(
        "household_members",
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_household_members_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_household_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("household_id", "user_id", name=op.f("pk_household_members")),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_tags_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("household_id", "name", name=op.f("uq_tags_household_id")),
    )
    op.create_table(
        "chore_assignees",
        sa.Column("chore_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chore_id"],
            ["chores.id"],
            name=op.f("fk_chore_assignees_chore_id_chores"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_chore_assignees_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("chore_id", "user_id", name=op.f("pk_chore_assignees")),
    )
    op.create_table(
        "chore_tags",
        sa.Column("chore_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chore_id"],
            ["chores.id"],
            name=op.f("fk_chore_tags_chore_id_chores"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_chore_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("chore_id", "tag_id", name=op.f("pk_chore_tags")),
    )
    # ### end Alembic commands ###

    # Seed a single default household, add every existing user to it, and give it
    # two starter tags. Real household/tag management arrives in a later step; for
    # now this is what lets chores work out of the box. (Tests build the schema from
    # metadata, not migrations, so this seed only affects real databases.)
    op.execute("INSERT INTO households (name) VALUES ('Household')")
    op.execute(
        "INSERT INTO household_members (household_id, user_id) "
        "SELECT h.id, u.id FROM households h CROSS JOIN users u"
    )
    op.execute(
        "INSERT INTO tags (household_id, name, color) "
        "SELECT id, 'deep-clean', '#0d9488' FROM households"
    )
    op.execute(
        "INSERT INTO tags (household_id, name, color) "
        "SELECT id, 'shared', '#7c6bf0' FROM households"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chore_tags")
    op.drop_table("chore_assignees")
    op.drop_table("tags")
    op.drop_table("household_members")
    op.drop_table("chores")
    op.drop_table("households")
    # ### end Alembic commands ###

    # create_table created these enum types implicitly; drop them explicitly.
    sa.Enum(name="repeat_period").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="assignment_type").drop(op.get_bind(), checkfirst=True)
