"""add chores.deleted_at soft delete

Revision ID: 367f5fe98e00
Revises: 12140d9e3c8e
Create Date: 2026-07-18 09:29:27.429674

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "367f5fe98e00"
down_revision: str | Sequence[str] | None = "12140d9e3c8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chores", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chores", "deleted_at")
    # ### end Alembic commands ###
