"""add users.avatar_path

Revision ID: 76ecbe8cb6a9
Revises: 88a12fbba959
Create Date: 2026-07-16 17:26:08.837447

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76ecbe8cb6a9"
down_revision: str | Sequence[str] | None = "88a12fbba959"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar_path", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_path")
    # ### end Alembic commands ###
