"""unique users.avatar_path

Revision ID: a7d3a6189295
Revises: 76ecbe8cb6a9
Create Date: 2026-07-16 18:08:30.473183

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7d3a6189295"
down_revision: str | Sequence[str] | None = "76ecbe8cb6a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_users_avatar_path"), "users", ["avatar_path"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_avatar_path"), "users", type_="unique")
    # ### end Alembic commands ###
