"""add stats query indexes

Revision ID: cf1c12f13d25
Revises: bc8bb308628f
Create Date: 2026-07-21 16:57:30.104702

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf1c12f13d25"
down_revision: str | Sequence[str] | None = "bc8bb308628f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_occurrence_status_completed_at",
        "chore_occurrences",
        ["status", "completed_at"],
        unique=False,
    )
    op.create_index(
        "ix_occurrence_status_scheduled_for",
        "chore_occurrences",
        ["status", "scheduled_for"],
        unique=False,
    )
    op.create_index(op.f("ix_chores_household_id"), "chores", ["household_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chores_household_id"), table_name="chores")
    op.drop_index("ix_occurrence_status_scheduled_for", table_name="chore_occurrences")
    op.drop_index("ix_occurrence_status_completed_at", table_name="chore_occurrences")
    # ### end Alembic commands ###
