"""add users theme and accent_color

Revision ID: d2fc5a73b3cd
Revises: a7d3a6189295
Create Date: 2026-07-16 20:48:17.513942

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2fc5a73b3cd"
down_revision: str | Sequence[str] | None = "a7d3a6189295"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("theme", sa.String(length=32), nullable=True))
    op.add_column("users", sa.Column("accent_color", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "accent_color")
    op.drop_column("users", "theme")
    # ### end Alembic commands ###
