"""add households.deleted_at soft delete

Revision ID: e0f788a32a8a
Revises: 989731c390a9
Create Date: 2026-07-17 19:35:27.752004

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0f788a32a8a"
down_revision: str | Sequence[str] | None = "989731c390a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("households", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("households", "deleted_at")
    # ### end Alembic commands ###
